---
# master configuration, just include all separate configuration files

- hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/python"
    arduino_version: 1.6.3
  tasks:
    - include: packages.yaml
    - include: user-setup.yaml
